# Generated by Django 2.2 on 2020-06-01 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_image',
        ),
    ]
