# Generated by Django 2.2 on 2020-04-29 04:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200428_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='votes_total',
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_summary',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
