# Generated by Django 2.2 on 2020-06-04 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_comment_comment_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='postID',
            new_name='post',
        ),
    ]
