# Generated by Django 2.2 on 2020-04-29 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200428_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='votes_total',
            field=models.IntegerField(default=0),
        ),
    ]
