# Generated by Django 2.0.2 on 2020-07-06 16:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_commentdvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_summary',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
