# Generated by Django 2.2 on 2020-10-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201023_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='static/user-default-image.png', null=True, upload_to='images/'),
        ),
    ]
