# Generated by Django 2.2 on 2020-10-29 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201023_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='../static/user-default-image.png', null=True, upload_to='images/'),
        ),
    ]
