# Generated by Django 2.2 on 2020-03-05 20:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='body',
        ),
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.TextField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_summary',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
